main: main.cpp Ball.cpp Tile.cpp Floor.cpp Scorebox.cpp Window.cpp Game.cpp
	g++ --std=c++11 Ball.cpp Tile.cpp Floor.cpp Scorebox.cpp Window.cpp Game.cpp main.cpp -o jump -lsfml-graphics -lsfml-window -lsfml-system
